language: go

go:
  - 1.16.x
  - tip

env:
  - GO111MODULE=on

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
